version: '3.8'
services:
  php:
    build: .
    container_name: c-php
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./website:/var/www/html
    links:
      - db
  db:
    image: mysql:latest
    container_name: c-mysql
    ports:
      - "3002:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=rroott